---
deployment:
  tasks:
    - export DEPLOYPATH=/home/candytex/public_html/dash/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp api.php $DEPLOYPATH
    - /bin/cp db.php $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp admin.php $DEPLOYPATH
    - /bin/cp admin_advanced.php $DEPLOYPATH
    - /bin/cp global.php $DEPLOYPATH
    - /bin/cp my_team.php $DEPLOYPATH
    - /bin/cp guide.php $DEPLOYPATH
    - /bin/cp import_users.php $DEPLOYPATH
    - /bin/cp schema.sql $DEPLOYPATH
    - /bin/cp update_db.php $DEPLOYPATH
    - /bin/cp init_admin.php $DEPLOYPATH

